name: 构建二进制

on:
  workflow_dispatch:  # 手动触发

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: 下载测试源码
      uses: actions/checkout@v3

    - name: 下载 Log-Adaptor 源码
      uses: actions/checkout@v3
      with:
        repository: arror/log-adaptor
        path: LA
        
    - name: 下载 OpenHarmony CommandLine
      uses: actions/download-artifact@v4
      with:
        name: commandline-tools
        github-token: ${{ secrets.GH_PAT }}
        run-id: 13959340710

    - name: 解压
      run: |
        unzip commandline-tools.zip
      
        
    - name: 构建二进制
      run: |
        chmod +x ./build.sh
        ./build.sh

    - name: 压缩构建产物
      run: |
        zip -r assets.zip output
      
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: assets
        path: assets.zip
