name: 构建二进制

on:
  workflow_dispatch:  # 手动触发

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: 下载测试源码
      uses: actions/checkout@v3

    - name: 下载 Go 源码仓库
      uses: actions/checkout@v3
      with:
        repository: arror/golang
        path: go-source

    - name: 构建 Go 并配置 Go 环境变量
      working-directory: go-source
      run: |
        cd src
        ./make.bash
        echo "GOROOT=${{ github.workspace }}/go-source" >> $GITHUB_ENV
        echo "${{ github.workspace }}/go-source/bin" >> $GITHUB_PATH
        which go
        go env
        
    - name: 下载 OpenHarmony CommandLine
      uses: actions/download-artifact@v4
      with:
        name: commandline-tools
        github-token: ${{ secrets.GH_PAT }}
        run-id: 13149180954

    - name: 解压
      run: |
        unzip commandline-tools.zip
      
        
    - name: 构建二进制
      run: |
        chmod +x ./build.sh
        ./build.sh

    - name: 压缩构建产物
      run: |
        zip -r assets.zip output
      
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: assets
        path: assets.zip
