name: 构建测试

on:
  workflow_dispatch:  # 手动触发

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: 下载 Go 源码仓库
      uses: actions/checkout@v3
      with:
        repository: arror/golang
        path: go-source

    - name: 从源码构建 Go
      working-directory: go-source
      run: |
        cd src
        ./make.bash

    - name: 下载 OpenHarmony CommandLine
      uses: actions/download-artifact@v4
      with:
        name: commandline-tools
        path: downloads
        github-token: ${{ secrets.GH_PAT }}
        run-id: 13149180954

    - name: 解压 OpenHarmony CommandLine
      run: |
        cd downloads
        echo -e "\n=== OpenHarmony CommandLine ==="
        unzip commandline-tools.zip

    - name: 下载当前源码
      uses: actions/checkout@v3
        
    - name: 构建二进制
      run: |
        echo "GOROOT=${{ github.workspace }}/go-source" >> $GITHUB_ENV
        echo "${{ github.workspace }}/go-source/bin" >> $GITHUB_PATH
        
        which go
        go env GOROOT
        go env GOOS GOARCH

        chmod +x ./build.sh
        
        ./build.sh

    - name: 压缩构建产物
      run: |
        zip -r assets.zip output
      
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: assets
        path: assets.zip
