name: 同步 OpenHarmony 命令行工具

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: '下载链接'
        required: true
        type: string
        
jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:

    - name: 下载文件
      run: |
        wget -O commandline-tools.zip "${{ github.event.inputs.download_url }}"
        
    - name: 上传文件
      uses: actions/upload-artifact@v4
      with:
        name: commandline-tools
        path: commandline-tools.zip
