name: 构建测试

on:
  workflow_dispatch:  # 手动触发
    inputs:
      go_run_id:
        description: 'Go构建工作流的运行ID'
        required: true
        type: string
      tools_run_id:
        description: '命令行工具工作流的运行ID'
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: 下载 Go 构建文件
      uses: actions/download-artifact@v4
      with:
        name: go-build.zip
        run-id: ${{ github.event.inputs.go_run_id }}
        path: downloads/go

    - name: 下载命令行工具
      uses: actions/download-artifact@v4
      with:
        name: commandline-tools.zip
        run-id: ${{ github.event.inputs.tools_run_id }}
        path: downloads/tools

    - name: 解压文件
      run: |
        echo "=== 解压 Go 构建文件 ==="
        cd downloads/go
        unzip go-build.zip
        
        echo -e "\n=== 解压命令行工具 ==="
        cd ../tools
        unzip commandline-tools.zip

    - name: 打印目录结构
      run: |
        echo "=== 文件结构 ==="
        tree -L 3 downloads/
